Master:
  Name: jenkins-master
  Image: hmcts/jenkins
  ImageTag: latest
  ImagePullPolicy: IfNotPresent
  Component: jenkins-master
  HostNetworking: false
  UseSecurity: true
  AdminUser: admin
  AdminPassword: formetoknowforyoutofindout
  JavaOpts: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 2048Mi
  ContainerEnv:
    - name: CASC_JENKINS_CONFIG
      value: >-
        https://raw.githubusercontent.com/hmcts/cnp-jenkins-config-as-code/kvcreds/jenkins.yaml
    - name: SECRETS
      value: /kvmnt
  UsePodSecurityContext: true
  ServicePort: 8080
  ServiceType: ClusterIP
  HostName: casc-jenkins.service.core-compute-saat.internal
  HealthProbes: true
  HealthProbesLivenessTimeout: 90
  HealthProbesReadinessTimeout: 60
  HealthProbeLivenessFailureThreshold: 12
  SlaveListenerPort: 50000
  DisabledAgentProtocols:
    - JNLP-connect
    - JNLP2-connect
  CSRF:
    DefaultCrumbIssuer:
      Enabled: true
      ProxyCompatability: true
  CLI: false
  SlaveListenerServiceType: ClusterIP
  SlaveListenerServiceAnnotations: {}
  LoadBalancerSourceRanges:
    - 0.0.0.0/0
  InstallPlugins: []
  InitScripts: null
  CustomConfigMap: false
  OverwriteConfig: false
  NodeSelector: {}
  Tolerations: {}
  PodAnnotations: {}
  Ingress:
    ApiVersion: extensions/v1beta1
    TLS: null
    Annotations:
      kubernetes.io/ingress.class: traefik
Agent:
  Enabled: false
  Image: jenkins/jnlp-slave
  ImageTag: 3.10-1
  CustomJenkinsLabels: []
  Component: jenkins-slave
  Privileged: false
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  AlwaysPullImage: false
  PodRetention: Never
  NodeSelector: {}
Persistence:
  Enabled: true
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 8Gi
  volumes:
    - name: slack-token
      flexVolume:
        driver: azure/kv
        secretRef:
          name: kvcreds
        options:
          usepodidentity: 'false'
          keyvaultname: infra-vault-sandbox
          keyvaultobjectname: slack-token
          keyvaultobjecttype: secret
          keyvaultobjectversion: 983c66afaa304c4d96da675dbcd01ceb
          resourcegroup: cnp-core-infra
          subscriptionid: bf308a5c-0624-4334-8ff8-8dca9fd43783
          tenantid: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
    - name: jenkins-reform-cnp
      flexVolume:
        driver: azure/kv
        secretRef:
          name: kvcreds
        options:
          usepodidentity: 'false'
          keyvaultname: infra-vault-sandbox
          keyvaultobjectname: hmcts-github-apikey-cnp
          keyvaultobjecttype: secret
          keyvaultobjectversion: f1dfc39a7d694152ba7cb3ca2aa6e02b
          resourcegroup: cnp-core-infra
          subscriptionid: bf308a5c-0624-4334-8ff8-8dca9fd43783
          tenantid: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
    - name: sonarcloud
      flexVolume:
        driver: azure/kv
        secretRef:
          name: kvcreds
        options:
          usepodidentity: 'false'
          keyvaultname: infra-vault-sandbox
          keyvaultobjectname: sonarcloud-api-token
          keyvaultobjecttype: secret
          keyvaultobjectversion: 96ab32caf2e241f0a94a5d749853fc7f
          resourcegroup: cnp-core-infra
          subscriptionid: bf308a5c-0624-4334-8ff8-8dca9fd43783
          tenantid: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
  mounts:
    - mountPath: /kvmnt
      name: slack-token
      readOnly: true
    - mountPath: /kvmnt
      name: jenkins-reform-cnp
      readOnly: true
    - mountPath: /kvmnt
      name: sonarcloud
      readOnly: true
NetworkPolicy:
  Enabled: false
  ApiVersion: extensions/v1beta1
rbac:
  install: true
  serviceAccountName: casc-jenkins
  roleRef: cluster-admin
  roleBindingKind: ClusterRoleBinding
